config/routes.rb
Rails.application.routes.draw do

  namespace :backoffice do
    get 'audios/index'
    get 'audios/new'
    get 'audios/create'
    get 'audios/destroy'
    # post 'messages', to: 'messages#create'
    get 'states', to: 'messages#states'
    # get 'posts', to: 'messages#posts'
  end

  namespace :site do
    get 'home/index'
  end

  namespace :api do
    get 'units/index', to: 'units#index'
    get 'units/states', to: 'units#states'
    get 'units/cities', to: 'units#cities'
    get 'units/:id', to: 'units#show'
    get 'courses/index', to: 'courses#index'
    get 'posts', to: 'posts#index'
    get 'posts/categories', to: 'posts#categories'
    get 'posts/categories/:id', to: 'posts#categories_show'
    get 'search', to: 'posts#search'
    get 'posts/:id', to: 'posts#show'
    get 'galleries/last', to: 'galleries#last'
    get 'pages/:id', to: 'pages#show'
    get 'question_answers', to: 'question_answers#index'
    post 'messages', to: 'messages#create'
    post 'discount_messages', to: 'discount_messages#create'


  end

  authenticate :unit do
    # root 'backoffice/dashboard#index'
    namespace :backoffice do
      get 'dashboard', to: 'dashboard#index'
      resources :weekly_challenges
      resources :audio_versions
      resources :weekly_challenge_bank_questions
      resources :galleries
      resources :units
      resources :students
      resources :courses
      resources :levels
      resources :errolments
      resources :posts
      resources :categories
      resources :pages
      resources :messages
      resources :discount_messages
      get 'sign_form', to: 'discount_messages#sign_form'

      resources :question_answers

      put 'errolments/change/:id', to: 'errolments#change_status', as: :change_status
      put 'student/errolments/change/:id', to: 'students#change_status', as: :student_change_status
      get 'student/lesson/delete/:id', to: 'students#delete_lesson', as: :student_delete_lesson
      get 'unit/achievements', to: 'student_achievements#by_unit', as: :student_achievements_unit
      get 'questions/attempts', to: 'questions#attempts', as: :questions_attempts
      get 'questions/attempts/delete/:id', to: 'questions#delete_attempt', as: :delete_questions_attempts

      resources :paths
      resources :questions
      resources :question_errors
      resources :achievements
      resources :student_achievements
      resources :audios
      resources :exams
      resources :books
      resources :student_books
      resources :instructions

    end
  end

  authenticate :student do
    root 'site/courses#index'

    namespace :site do
      resources :quizzes
      get '/quizzes/courses/:id', to: 'quizzes#course', as: 'course'
      get '/quizzes/level/:id', to: 'quizzes#level', as: 'level'

      post '/quizzes/start_lesson', to: 'quizzes#start_lesson', as: :start_lesson
      # map to custom action
      post '/quizzes/report', to: 'quizzes#report', as: :report_question
      resources :weekly_challenge_quizzes
      resources :student_instructions


      patch 'students', to: 'students#update'
      get 'simulados', to: 'simulados#index'
      get 'audios', to: 'audios#index'

      get '/courses/:id/audios', to: 'audios#course', as: 'course_audio'
      get '/courses/:id', to: 'courses#show', as: 'show_course'

      get '/courses/:id/books', to: 'books#course', as: 'course_book'
      get '/courses/:id/books/:book_id', to: 'books#index', as: 'show_book'

      post 'book_save_page', to: 'books#save_page'
    end
  end

  devise_for :students, controllers: { sessions: 'students/sessions' }
  devise_for :units, controllers: { sessions: 'units/sessions' }



end

app/models/backoffice.rb
module Backoffice
  def self.table_name_prefix
    'backoffice_'
  end
end

app/models/discount_message.rb
class DiscountMessage < ApplicationRecord
end

app/controllers/api/discount_messages_controller.rb
class Api::DiscountMessagesController < BackofficeController

  # POST /messages
  def create
    new_message_params = message_params.except(:hasOnlineClasses)

    if (message_params[:hasOnlineClasses])
      selected_unit = Unit.left_joins(:students).where(has_online_classes: true).group(:id).select('COUNT(students.id) as students_count, units.id, units.email, units.email_message').order('students_count ASC').first
      new_message_params[:unidade] = selected_unit[:email_message] ? selected_unit[:email_message] : selected_unit[:email]
    end
    
    @message = Message.new(new_message_params)

    if @message.save
      UserMessageMailer.send_message_email(@message).deliver
      render json: @message, status: :created
    else
      render json: @message.errors, status: :unprocessable_entity
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_message
    @message = Message.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def message_params
    params.require(:message).permit(:nome, :email, :telefone, :unidade, :curso, :assunto, :hasOnlineClasses)
  end

end

app/controllers/backoffice/achievements_controller.rb
class Backoffice::AchievementsController < BackofficeController
    before_action :set_achievement, only: [:show, :edit, :update, :destroy]


    def index
        @achievements = Achievement.all
    end

    def new
        @achievement = Achievement.new
    end

    def create
        @achievement = Achievement.new(achievement_params)

        if @achievement.save
            redirect_to backoffice_achievements_path, notice: "The achievement #{@achievement.description} has been created."
        else
            render "new"
        end
    end
    
    def update
        respond_to do |format|
          if @achievement.update(achievement_params)
            format.html { redirect_to backoffice_achievement_path(@achievement), notice: 'achievement was successfully updated.' }
            format.json { render :show, status: :ok, location: @achievement }
          else
            format.html { render :edit }
            format.json { render json: @achievement.errors, status: :unprocessable_entity }
          end
        end
    end

    def destroy
        @achievement = Achievement.find(params[:id])
        @achievement.destroy
        redirect_to backoffice_achievements_path, notice:  "The achievement #{@achievement.description} has been deleted."
    end

    private
    def set_achievement
        @achievement = Achievement.find(params[:id])
    end

    def achievement_params
        params.require(:achievement).permit(:description, :badge_path)
    end
end

app/controllers/backoffice/addresses_controller.rb
class Backoffice::AddressesController < BackofficeController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:street, :neighborhood, :number, :state, :city, :unit_id,
        :latitude, :longitude)
    end
end

app/controllers/backoffice/api_controller.rb
class Backoffice::ApiController < BackofficeController
  def posts
    @posts = Post.all.reverse_order
    render json: @posts, :include => :categories
  end


end

app/controllers/backoffice/audio_versions_controller.rb
class Backoffice::AudioVersionsController < BackofficeController

  before_action :set_audio_version, only: [:show, :edit, :update, :destroy]

  # GET /audio_versions
  # GET /audio_versions.json
  def index
    @audio_versions = AudioVersion.all
  end

  # GET /audio_versions/1
  # GET /audio_versions/1.json
  def show
  end

  # GET /audio_versions/new
  def new
    @audio_version = AudioVersion.new
  end

  # GET /audio_versions/1/edit
  def edit
  end

  # POST /audio_versions
  # POST /audio_versions.json
  def create
    @audio_version = AudioVersion.new(audio_version_params)

    respond_to do |format|
      if @audio_version.save
        format.html { redirect_to backoffice_level_path(@audio_version.level), notice: 'Audio version was successfully created.' }
        format.json { render :show, status: :created, location: @audio_version }
      else
        format.html { render :new }
        format.json { render json: @audio_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /audio_versions/1
  # PATCH/PUT /audio_versions/1.json
  def update
    respond_to do |format|
      if @audio_version.update(audio_version_params)
        format.html { redirect_to backoffice_audio_versions_path, notice: 'Audio version was successfully updated.' }
        format.json { render :show, status: :ok, location: @audio_version }
      else
        format.html { render :edit }
        format.json { render json: @audio_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /audio_versions/1
  # DELETE /audio_versions/1.json
  def destroy
    @audio_version.destroy
    respond_to do |format|
      format.html { redirect_to backoffice_audio_versions_path, notice: 'Audio version was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_audio_version
      @audio_version = AudioVersion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def audio_version_params
      params.require(:audio_version).permit(:title, :level_id)
    end
end

app/controllers/backoffice/audios_controller.rb
class Backoffice::AudiosController < BackofficeController
  before_action :set_audio, only: [:show, :edit, :update, :destroy]


  def index
    @audios = Audio.all
  end

  def new
    @audio = Audio.new
  end

  def edit
  end

  def create
    @audio = Audio.new(audio_params)

    if @audio.save
      redirect_to backoffice_audios_path, notice: "The audio #{@audio.title} has been uploaded."
    else
      render "new"
    end
  end

  def update
    respond_to do |format|
        if @audio.update(audio_params)
            format.html { redirect_to backoffice_audios_path, notice: 'O audio foi atualizado.' }
            format.json { render :show, status: :ok, location: @audio }
        else
            format.html { render :edit }
            format.json { render json: @audio.errors, status: :unprocessable_entity }
        end
    end
  end

  def destroy
    @audio = Audio.find(params[:id])
    @audio.destroy
    redirect_to backoffice_audios_path, notice:  "The audio #{@audio.title} has been deleted."
  end

private
  def set_audio
    @audio = Audio.find(params[:id])
  end

  def audio_params
    params.require(:audio).permit(:title, :attachment, :level_id, :audio_version_id )
  end
end

app/controllers/backoffice/books_controller.rb
class Backoffice::BooksController < BackofficeController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
    authorize @book
  end

  def edit
    @book_options = Book.all
    authorize @book
  end

  def create
    @book = Book.new(book_params)
    authorize @book

    respond_to do |format|
      if @book.save
          format.html { redirect_to new_backoffice_book_path, notice: "O livro #{@book.course_level_book} foi adicionado." }
          format.json { render :show, status: :created, location: new_backoffice_book_path }
      else
          format.html { render :new }
          format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @book
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to new_backoffice_book_path, notice: "O livro #{@book.course_level_book} foi atualizado." }
        format.json { render :show, status: :ok, location: new_backoffice_book_path }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @book
    @book.destroy
    redirect_to new_backoffice_book_path, notice:  "O livro #{@book.course_level_book} foi deletado."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      puts 'here', params
      params[:id] = params[:id] ? params[:id] : params[:book][:id]
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :level_id, :attachment, :cover, :downloadable)
    end
end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  has_scope :keyword

  def index
    categories = apply_scopes(Category).all
    @pagy, @categories = pagy(categories, items: 6)
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
    @category
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to backoffice_category_path(@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: backoffice_category_path(@category) }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to backoffice_category_path(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to backoffice_categories_path, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:title, :body)
  end

end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController

  def index
    @greatest_students_br = Student.order("points DESC").first(30)
    @greatest_students_unit = current_unit.students.order("points DESC").first(30)   
    
    if current_unit.admin == true
      @units = Unit.all
    else
      @units = Unit.where(id: current_unit.id)
    end

    @levels = Level.all
     
  end
end

app/controllers/backoffice/discount_messages_controller.rb
class Backoffice::DiscountMessagesController < BackofficeController

  before_action :set_message, only: [:show, :edit, :update, :destroy]

  def index
    @messages = DiscountMessage.where(curso: [nil, ""]).reverse_order
  end

  def sign_form
    @messages = Message.where.not(curso: [nil, ""]).reverse_order
  end

  def show
  end

  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to backoffice_messages_path(), notice: 'A Lição foi excluída com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_message
    @message = DiscountMessage.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def message_params
    params.require(:message).permit(:nome, :email, :telefone, :unidade, :assunto, :corpo)
  end

end

app/views/backoffice/discount_messages/_form.html.erb
<%= form_with(model: question_answer, local: true, url: path) do |form| %>
  <% if question_answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question_answer.errors.count, "error") %> prohibited this question_answer from being saved:</h2>

      <ul>
      <% question_answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="field form-group col-md-12">
      <%= form.label "Pergunta" %>
      <%= form.text_field :question, class: "form-control" %>
    </div>

    <div class="field form-group col-md-12">
      <%= form.label "Resposta" %>
      <%= form.text_area :answer, 'data-provider': :summernote %>
    </div>
  </div>
  <div class="row">
    <div class="actions  col-md-12">
      <%= form.submit "Enviar", :class => "btn btn-default" %>
    </div>
  </div>


<% end %>

app/views/backoffice/discount_messages/edit.html.erb
<h1 class="page-header">Editar FAQ</h1>

<%= render 'form', question_answer: @question_answer, path: backoffice_question_answer_path %>

app/views/backoffice/discount_messages/index.html.erb
<h1 class="page-header">Formulário de Desconto</h1>

    <div class="col-md-12">

        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                      <th>id</th>
                      <th>Nome</th>
                      <th>Telefone</th>
                      <th>Data</th>
                      <th></th>
                    </tr>
                </thead>
                <tbody>
                    <% @messages.each do |message| %>
                        <tr>
                          <td><%= message.id %></td>
                          <td><%= message.nome %></td>
                          <td><%= message.telefone %></td>
                          <td><%= message.created_at.strftime("%d/%m/%Y às %T")  %></td>
                          <td>
                              <%= link_to backoffice_discount_message_path(message), class: "btn btn-default btn-circle" do %>
                                  <i class="fa fa-search"></i>
                              <% end %>
                          </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>

        </div>
    </div>

app/views/backoffice/discount_messages/new.html.erb
<h1 class="page-header">Nova FAQ</h1>

<%= render 'form', question_answer: @question_answer, path: backoffice_question_answers_path %>

app/views/backoffice/discount_messages/show.html.erb
<h1 class="page-header">Resposta do Formulário: <%= @message.id %></h1>

<div class="col-md-12">
  <div class="panel panel-default ">
    <div class="panel-heading">
      <%= @message.id %>
    </div>
    <div class="panel-body">
      <p>
        <strong>Nome:</strong>
        <%= @message.nome %>
      </p>
      <p>
        <strong>Email:</strong>
        <%= @message.email %>
      </p>
      <p>
        <strong>Telefone:</strong>
        <%= @message.telefone %>
      </p>
      <p>
        <strong>Unidade:</strong>
        <%= @message.unidade %>
      </p>

    </div>

  </div>
</div>

app/views/backoffice/discount_messages/sign_form.html.erb
<h1 class="page-header">Formulário de Inscrição</h1>

    <div class="col-md-12">

        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                      <th>id</th>
                      <th>Nome</th>
                      <th>Telefone</th>
                      <th>Unidade</th>
                      <th>Curso</th>
                      <th>Data</th>
                      <th></th>
                    </tr>
                </thead>
                <tbody>
                    <% @messages.each do |message| %>
                        <tr>
                          <td><%= message.id %></td>
                          <td><%= message.nome %></td>
                          <td><%= message.telefone %></td>
                          <td><%= message.unidade %></td>
                          <td><%= message.curso %></td>
                          <td><%= message.created_at.strftime("%d/%m/%Y às %T")  %></td>
                          <td>
                              <%= link_to backoffice_discount_message_path(message), class: "btn btn-default btn-circle" do %>
                                  <i class="fa fa-search"></i>
                              <% end %>
                          </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>

        </div>
    </div>