config/routes.rb
Rails.application.routes.draw do

  namespace :backoffice do
    get 'audios/index'
    get 'audios/new'
    get 'audios/create'
    get 'audios/destroy'
    # post 'messages', to: 'messages#create'
    get 'states', to: 'messages#states'
    # get 'posts', to: 'messages#posts'
  end

  namespace :site do
    get 'home/index'
  end

  namespace :api do
    get 'units/index', to: 'units#index'
    get 'units/states', to: 'units#states'
    get 'units/cities', to: 'units#cities'
    get 'units/:id', to: 'units#show'
    get 'courses/index', to: 'courses#index'
    get 'posts', to: 'posts#index'
    get 'posts/categories', to: 'posts#categories'
    get 'posts/categories/:id', to: 'posts#categories_show'
    get 'search', to: 'posts#search'
    get 'posts/:id', to: 'posts#show'
    get 'galleries/last', to: 'galleries#last'
    get 'pages/:id', to: 'pages#show'
    get 'question_answers', to: 'question_answers#index'
    post 'messages', to: 'messages#create'
    post 'discount_messages', to: 'discount_messages#create'


  end

  authenticate :unit do
    # root 'backoffice/dashboard#index'
    namespace :backoffice do
      get 'dashboard', to: 'dashboard#index'
      resources :weekly_challenges
      resources :audio_versions
      resources :weekly_challenge_bank_questions
      resources :galleries
      resources :units
      resources :students
      resources :courses
      resources :levels
      resources :errolments
      resources :posts
      resources :categories
      resources :pages
      resources :messages
      resources :discount_messages
      get 'sign_form', to: 'discount_messages#sign_form'

      resources :question_answers

      put 'errolments/change/:id', to: 'errolments#change_status', as: :change_status
      put 'student/errolments/change/:id', to: 'students#change_status', as: :student_change_status
      get 'student/lesson/delete/:id', to: 'students#delete_lesson', as: :student_delete_lesson
      get 'unit/achievements', to: 'student_achievements#by_unit', as: :student_achievements_unit
      get 'questions/attempts', to: 'questions#attempts', as: :questions_attempts
      get 'questions/attempts/delete/:id', to: 'questions#delete_attempt', as: :delete_questions_attempts

      resources :paths
      resources :questions
      resources :question_errors
      resources :achievements
      resources :student_achievements
      resources :audios
      resources :exams
      resources :books
      resources :student_books
      resources :instructions

    end
  end

  authenticate :student do
    root 'site/courses#index'

    namespace :site do
      resources :quizzes
      get '/quizzes/courses/:id', to: 'quizzes#course', as: 'course'
      get '/quizzes/level/:id', to: 'quizzes#level', as: 'level'

      post '/quizzes/start_lesson', to: 'quizzes#start_lesson', as: :start_lesson
      # map to custom action
      post '/quizzes/report', to: 'quizzes#report', as: :report_question
      resources :weekly_challenge_quizzes
      resources :student_instructions


      patch 'students', to: 'students#update'
      get 'simulados', to: 'simulados#index'
      get 'audios', to: 'audios#index'

      get '/courses/:id/audios', to: 'audios#course', as: 'course_audio'
      get '/courses/:id', to: 'courses#show', as: 'show_course'

      get '/courses/:id/books', to: 'books#course', as: 'course_book'
      get '/courses/:id/books/:book_id', to: 'books#index', as: 'show_book'

      post 'book_save_page', to: 'books#save_page'
    end
  end

  devise_for :students, controllers: { sessions: 'students/sessions' }
  devise_for :units, controllers: { sessions: 'units/sessions' }



end

app/models/backoffice.rb
module Backoffice
  def self.table_name_prefix
    'backoffice_'
  end
end

app/models/student_achievement.rb
class StudentAchievement < ApplicationRecord
    belongs_to :student
    belongs_to :achievement

    
end

app/controllers/backoffice/achievements_controller.rb
class Backoffice::AchievementsController < BackofficeController
    before_action :set_achievement, only: [:show, :edit, :update, :destroy]


    def index
        @achievements = Achievement.all
    end

    def new
        @achievement = Achievement.new
    end

    def create
        @achievement = Achievement.new(achievement_params)

        if @achievement.save
            redirect_to backoffice_achievements_path, notice: "The achievement #{@achievement.description} has been created."
        else
            render "new"
        end
    end
    
    def update
        respond_to do |format|
          if @achievement.update(achievement_params)
            format.html { redirect_to backoffice_achievement_path(@achievement), notice: 'achievement was successfully updated.' }
            format.json { render :show, status: :ok, location: @achievement }
          else
            format.html { render :edit }
            format.json { render json: @achievement.errors, status: :unprocessable_entity }
          end
        end
    end

    def destroy
        @achievement = Achievement.find(params[:id])
        @achievement.destroy
        redirect_to backoffice_achievements_path, notice:  "The achievement #{@achievement.description} has been deleted."
    end

    private
    def set_achievement
        @achievement = Achievement.find(params[:id])
    end

    def achievement_params
        params.require(:achievement).permit(:description, :badge_path)
    end
end

app/controllers/backoffice/addresses_controller.rb
class Backoffice::AddressesController < BackofficeController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:street, :neighborhood, :number, :state, :city, :unit_id,
        :latitude, :longitude)
    end
end

app/controllers/backoffice/api_controller.rb
class Backoffice::ApiController < BackofficeController
  def posts
    @posts = Post.all.reverse_order
    render json: @posts, :include => :categories
  end


end

app/controllers/backoffice/audio_versions_controller.rb
class Backoffice::AudioVersionsController < BackofficeController

  before_action :set_audio_version, only: [:show, :edit, :update, :destroy]

  # GET /audio_versions
  # GET /audio_versions.json
  def index
    @audio_versions = AudioVersion.all
  end

  # GET /audio_versions/1
  # GET /audio_versions/1.json
  def show
  end

  # GET /audio_versions/new
  def new
    @audio_version = AudioVersion.new
  end

  # GET /audio_versions/1/edit
  def edit
  end

  # POST /audio_versions
  # POST /audio_versions.json
  def create
    @audio_version = AudioVersion.new(audio_version_params)

    respond_to do |format|
      if @audio_version.save
        format.html { redirect_to backoffice_level_path(@audio_version.level), notice: 'Audio version was successfully created.' }
        format.json { render :show, status: :created, location: @audio_version }
      else
        format.html { render :new }
        format.json { render json: @audio_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /audio_versions/1
  # PATCH/PUT /audio_versions/1.json
  def update
    respond_to do |format|
      if @audio_version.update(audio_version_params)
        format.html { redirect_to backoffice_audio_versions_path, notice: 'Audio version was successfully updated.' }
        format.json { render :show, status: :ok, location: @audio_version }
      else
        format.html { render :edit }
        format.json { render json: @audio_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /audio_versions/1
  # DELETE /audio_versions/1.json
  def destroy
    @audio_version.destroy
    respond_to do |format|
      format.html { redirect_to backoffice_audio_versions_path, notice: 'Audio version was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_audio_version
      @audio_version = AudioVersion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def audio_version_params
      params.require(:audio_version).permit(:title, :level_id)
    end
end

app/controllers/backoffice/audios_controller.rb
class Backoffice::AudiosController < BackofficeController
  before_action :set_audio, only: [:show, :edit, :update, :destroy]


  def index
    @audios = Audio.all
  end

  def new
    @audio = Audio.new
  end

  def edit
  end

  def create
    @audio = Audio.new(audio_params)

    if @audio.save
      redirect_to backoffice_audios_path, notice: "The audio #{@audio.title} has been uploaded."
    else
      render "new"
    end
  end

  def update
    respond_to do |format|
        if @audio.update(audio_params)
            format.html { redirect_to backoffice_audios_path, notice: 'O audio foi atualizado.' }
            format.json { render :show, status: :ok, location: @audio }
        else
            format.html { render :edit }
            format.json { render json: @audio.errors, status: :unprocessable_entity }
        end
    end
  end

  def destroy
    @audio = Audio.find(params[:id])
    @audio.destroy
    redirect_to backoffice_audios_path, notice:  "The audio #{@audio.title} has been deleted."
  end

private
  def set_audio
    @audio = Audio.find(params[:id])
  end

  def audio_params
    params.require(:audio).permit(:title, :attachment, :level_id, :audio_version_id )
  end
end

app/controllers/backoffice/books_controller.rb
class Backoffice::BooksController < BackofficeController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
    authorize @book
  end

  def edit
    @book_options = Book.all
    authorize @book
  end

  def create
    @book = Book.new(book_params)
    authorize @book

    respond_to do |format|
      if @book.save
          format.html { redirect_to new_backoffice_book_path, notice: "O livro #{@book.course_level_book} foi adicionado." }
          format.json { render :show, status: :created, location: new_backoffice_book_path }
      else
          format.html { render :new }
          format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @book
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to new_backoffice_book_path, notice: "O livro #{@book.course_level_book} foi atualizado." }
        format.json { render :show, status: :ok, location: new_backoffice_book_path }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @book
    @book.destroy
    redirect_to new_backoffice_book_path, notice:  "O livro #{@book.course_level_book} foi deletado."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      puts 'here', params
      params[:id] = params[:id] ? params[:id] : params[:book][:id]
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :level_id, :attachment, :cover, :downloadable)
    end
end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  has_scope :keyword

  def index
    categories = apply_scopes(Category).all
    @pagy, @categories = pagy(categories, items: 6)
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
    @category
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to backoffice_category_path(@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: backoffice_category_path(@category) }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to backoffice_category_path(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to backoffice_categories_path, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:title, :body)
  end

end

app/controllers/backoffice/courses_controller.rb
class Backoffice::CoursesController < BackofficeController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  def index
    @courses = Course.all
  end

  def show
  end

  def new
    @course = Course.new
    @course.levels.build

    authorize @course
  end

  def edit
    authorize @course
  end

  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
          format.html { redirect_to backoffice_course_path(@course), notice: 'Course was successfully created.' }
          format.json { render :show, status: :created, location: backoffice_course_path(@course) }
      else
          format.html { render :new }
          format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @course.update(course_params)
          format.html { redirect_to backoffice_courses_path(@course), notice: 'Course was successfully updated.' }
          format.json { render :show, status: :ok, location: @course }
      else
          format.html { render :edit }
          format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @course
    @course.destroy
    respond_to do |format|
        format.html { redirect_to backoffice_courses_path, notice: 'Course was successfully destroyed.' }
        format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def course_params
    params.require(:course).permit(
      :title,
      :language,
      :description,
      :level_id,
      :course_flag,
      :site_flag,
      :published,
      :cover,
      :inner,
      :order,
      :course_id,
      levels_attributes: [:id, :title, :_destroy]).merge(unit_id: current_unit.id)
  end

end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController

  def index
    @greatest_students_br = Student.order("points DESC").first(30)
    @greatest_students_unit = current_unit.students.order("points DESC").first(30)   
    
    if current_unit.admin == true
      @units = Unit.all
    else
      @units = Unit.where(id: current_unit.id)
    end

    @levels = Level.all
     
  end
end

app/views/backoffice/student_achievements/_form.html.erb
<%= form_with(model: student_achievement, local: true, url: path ) do |form| %>
  <% if student_achievement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student_achievement.errors.count, "error") %> prohibited this errolment from being saved:</h2>

      <ul>
      <% student_achievement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group col-md-6">
    <%= form.label "Aluno" %>
    <%= collection_select(:student_achievement, :student_id, Student.all, :id, :name, {:prompt => true}, {:class=>'js-example-basic-single form-control'}) %>
  </div>

  <div class="field form-group col-md-6">
    <%= form.label "Nível" %>
    <%= collection_select(
                          :student_achievement, 
                          :achievement_id, 
                          Achievement.all, 
                          :id, 
                          :description, 
                          {:prompt => true}, 
                          {:class=>'form-control'}) 
                        %>
  </div>

  <div class="actions  col-md-12">
    <%= form.submit "Enviar", :class => "btn btn-default" %>
  </div>
<% end %>

app/views/backoffice/student_achievements/by_unit.html.erb
<h1 class="page-header">Conquistas por aluno da unidade</h1>

<div class="row">
<div class="col-md-12">
  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
          <tr>
            <th>Aluno</th>
            <th>Conquista</th>
            <th>Badge</th>
            <th>Data da conquista</th>
          </tr>
      </thead>
      <tbody>
      <% @student_achievements.each do |student_achievement| %>
        <tr>
          <td><%= student_achievement.student.name%></td>
          <td><%= student_achievement.achievement.description %></td>
          <td><%= image_tag student_achievement.achievement.badge_path, width: "30px" %></td>
          <td><%= student_achievement.created_at.strftime("%d/%m/%Y às %T") %></td>
       
          
        </tr>
      <% end %>
          
      </tbody>
    </table>
  </div>
</div>
<br>



</div>  

app/views/backoffice/student_achievements/edit.html.erb
<h1 class="page-header">Etitar Conquista de Aluno</h1>

<%= render 'form', student_achievement: @student_achievement, path: backoffice_student_achievement_path %>

app/views/backoffice/student_achievements/index.html.erb
<h1 class="page-header">Conquistas por aluno</h1>

<div class="row">
<div class="col-md-12">
  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
          <tr>
            <th>ID</th>
            <th>Aluno</th>
            <th>Conquista</th>
            <th>Badge</th>
            <th>Data da conquista</th>
            <th ><%= @student_achievements.length %> resultados</th>
          </tr>
      </thead>
      <tbody>
      <% @student_achievements.each do |student_achievement| %>
        <tr>
          <td><%= student_achievement.id%></td>
          <td><%= student_achievement.student.name%></td>
          <td><%= student_achievement.achievement.description %></td>
          <td><%= image_tag student_achievement.achievement.badge_path, width: "30px" %></td>
          <td><%= student_achievement.created_at.strftime("%d/%m/%Y às %T") %></td>
          <td>
            <%= link_to backoffice_student_achievement_path(student_achievement), class: "btn btn-default btn-circle" do %>
              <i class="fa fa-search"></i>
            <% end %>
          </td>
          
        </tr>
      <% end %>
          
      </tbody>
    </table>
  </div>
</div>

<div class="col-md-12">
    <div style="text-align: center;">      
    <%# pagy_bootstrap_nav(@pagy).html_safe %>
    </div>
</div>  

<br>

<%= link_to 'Nova Conquista', new_backoffice_student_achievement_path %>


</div>  

app/views/backoffice/student_achievements/new.html.erb
<h1 class="page-header">Nova Conquista de Aluno</h1>

<%= render 'form', student_achievement: @student_achievement, path: backoffice_student_achievements_path %>

app/views/backoffice/student_achievements/show.html.erb
<h1 class="page-header">Conquista</h1>
<div class="col-md-6">
  <div class="panel panel-default ">
    <div class="panel-heading">
      <%= @student_achievement.achievement.description %> - <%= @student_achievement.student.name %>
    </div>
    <div class="panel-body">
      <p>
        <%= image_tag @student_achievement.achievement.badge_path, width: "100px" %>
      </p>
      <p>
        <strong>Level:</strong>
        <%= @student_achievement.achievement.description %>
      </p>

      <p>
        <strong>Estudante:</strong>
        <%= @student_achievement.student.name %>
      </p>
  
      
        <p>
        <strong>Data da conquista:</strong>
        <%= @student_achievement.created_at.strftime("%d/%m/%Y às %T") %>
      </p>
      <%= link_to 'Editar', edit_backoffice_student_achievement_path(@student_achievement), class: "btn btn-outline btn-primary" %>
      <%= link_to 'Excluir', backoffice_student_achievement_path(@student_achievement),  class: "btn btn-outline btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>   
  </div>
</div>